### ISSUE TITLE
All objects returned by API should have all their fields.

### ISSUE THREAD

**Issue by olzraiti** [TheSoftwareFactory/lokki-server#100]
Now many objects returned by API don't contain their own ids and other fields. API returns objects as a map, where id is the key, and object is the value. At front end you must keep track of object ids by keeping a map synchronized. There are also many 10-100 rows long utility-methods that simply return some model objects field. We wouldn't need these if the models could just contain all their fields.

**Comment by ffagerho** [comment]
Addressed by #108, #109, and #110.
