### ISSUE TITLE
Find suspicious things from source code

### ISSUE THREAD

**Issue by josalmi** [TheSoftwareFactory/lokki-server#14]
Files are filled with admin passwords and passphrases to keys.

**Comment by Kauhsa** [comment]
I think this was mostly fixed while working on issue #18, but might still deserve another look to be sure.

**Comment by ffagerho** [comment]
The only thing I could find was in lib/appleNotificationService.js, where there are some outdated credentials for apple notifications

**Comment by ffagerho** [comment]
So if you review this and agree, go ahead and close the issue.

**Comment by DocV** [comment]
I looked through the code and didn't find anything, closing the issue.

**Comment by josalmi** [comment]
https://github.com/TheSoftwareFactory/lokki-server/blob/master/lib/appleNotificationService.js#L41
