### ISSUE TITLE
Figure out how to evaluate backend performance

### ISSUE THREAD

**Issue by ffagerho** [TheSoftwareFactory/lokki-server#36]
_From @ffagerho on February 16, 2015 14:18_

_Copied from original issue: TheSoftwareFactory/lokki-android#153_

**Comment by ffagerho** [comment]
_From @josalmi on February 16, 2015 23:30_

Does this belong in lokki-android?

**Comment by Kauhsa** [comment]
Does this mean constant monitoring or just that we make sure that the backend can handle some decent load before launching?

**Comment by Kauhsa** [comment]
I'll note though that I wouldn't be terribly worried about anything else than our database size – currently we have something like 50 accounts on the server (by the statistics that can be read with admin account) and we have used 13.33% of our free database limit. So it might be a bit too small if this thing actually gets some users.

**Comment by ffagerho** [comment]
The most realistic solution here is to watch the Heroku backend and when it seems we are reaching our limits, we can either a) upgrade to a more performant plan or b) find specific performance problems and fix them. This issue is too broad to be useful, closing.
