### ISSUE TITLE
Old email confirmation link works after new one is sent

### ISSUE THREAD

**Issue by eemihauk** [TheSoftwareFactory/lokki-server#37]

**Comment by Grandi** [comment]
A bit difficult to start working on these email issues since for some reason the server doesn't even send any confirmation emails in the first place. Or is there something that I should be aware of?

**Comment by josalmi** [comment]
See: https://github.com/TheSoftwareFactory/lokki-server/blob/master/config/development.json#L10

Also SendGrid is sometimes slow so email might take up to 24 hours in production. Even though I haven't seen this being a problem for long long time.

**Comment by DocV** [comment]
Fixed in #71
