### ISSUE TITLE
Registrations should require confirmation

### ISSUE THREAD

**Issue by ffagerho** [TheSoftwareFactory/lokki-server#66]
Registration should be a two-step process:

1. The user enters their email address in the Android app. The app calls the backend and either the user is logged in (account existed) or a new account is created and the user is logged in (account did not exist). When a new account is created, it is flagged as unconfirmed. Also, account creation causes a welcome email to be sent.
2. The welcome email contains a confirmation link that is valid for 24 hours. Unless the user clicks the link within that time, the account expires and is deleted. However, the user can still use the app normally with an unconfirmed account (until it expires). When the user clicks the link, they are shown a web page that tells them their account is now activated. If the page loads successfully, the account is flagged as confirmed.

**Comment by DocV** [comment]
We'll know if this works at October 15th, 14:40

**Comment by DocV** [comment]
Seems to be working properly as of #85
